export const GET_ALL_RECIPES = 'GET_ALL_RECIPES'
export const SEARCH_BY_ID = 'SEARCH_BY_ID'
export const FILTER_TYPE_DIETS = 'FILTER_TYPE_DIETS'
export const GET_ALL_TYPES = 'GET_ALL_TYPES'
export const ORDER_RECIPES = 'ORDER_RECIPES'
export const CREATE_RECIPES = 'CREATE_RECIPES'


